# Generated by Django 3.1.7 on 2021-03-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineBot', '0002_user_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='demo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
