# Generated by Django 3.1.7 on 2021-03-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineBot', '0003_user_demo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='demo',
            new_name='memo',
        ),
    ]
