# Generated by Django 3.1.7 on 2021-03-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineBot', '0004_auto_20210315_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
