# Generated by Django 3.1.7 on 2021-03-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineBot', '0005_auto_20210315_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=30, null=True)),
                ('date', models.CharField(max_length=15)),
                ('prices', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LunchOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('order', models.PositiveSmallIntegerField(null=True)),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineBot.user')),
            ],
        ),
    ]
