# Generated by Django 3.1.7 on 2021-03-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineBot', '0006_lunchmenu_lunchorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchmenu',
            name='avalible',
            field=models.BooleanField(default=False),
        ),
    ]
