# Generated by Django 3.1.7 on 2021-03-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineBot', '0007_lunchmenu_avalible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchmenu',
            name='photo_url',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
