# Generated by Django 3.1.7 on 2021-03-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineBot', '0008_auto_20210320_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchmenu',
            name='avalible',
            field=models.BooleanField(default=True),
        ),
    ]
