# Generated by Django 3.1.7 on 2021-03-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineBot', '0009_auto_20210320_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchorder',
            name='price',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
