# Generated by Django 3.1.7 on 2021-03-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineBot', '0010_lunchorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchorder',
            name='date',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lunchmenu',
            name='date',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
